# Default values for ums-rest.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 825303761615.dkr.ecr.ap-southeast-1.amazonaws.com/ums-rest
  tag: stable
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

hpa:
  enabled: true
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 75

annotations:
  iam.amazonaws.com/role: app-ums-rest

deployment:
  annotations:
    sidecar.jaegertracing.io/inject: "true"

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: private-nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Request-Id: $req_id";
      location /actuator {
        deny all;
        return 403;
      }


metrics:
  enabled: true
  serviceMonitor:
    enabled: true
  prometheusRule:
    enabled: false
    rules: []

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
#   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
