{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "ums.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "ums.name" . }}
    helm.sh/chart: {{ include "ums.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  endpoints:
    - port: http
      path: "/actuator/prometheus"
      interval: 10s
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ums.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}