server:
  host: localhost
  port: ${PORT:8080}
  error:
    whitelabel:
      enabled: false

spring.application:
  name: ums-rest

spring.mvc:
  throw-exception-if-no-handler-found: true
  favicon:
    enabled: false

spring.jpa:
  open-in-view: false
  database:
  properties:
    hibernate:
      jdbc.lob.non_contextual_creation: true
      jdbc.time_zone: UTC
      temp.use_jdbc_metadata_defaults: false
  #      show_sql: true
  #      format_sql: true
  hibernate:
    ddl-auto: validate

spring:
  datasource:
    url:
    username:
    password:
    driver-class-name: org.postgresql.Driver
    druid:
      # 初始化配置
      initial-size: 3
      # 最小连接数
      min-idle: 3
      # 最大连接数
      max-active: 15
      # 获取连接超时时间
      max-wait: 5000
      # 连接有效性检测时间
      time-between-eviction-runs-millis: 90000
      # 最大空闲时间
      min-evictable-idle-time-millis: 1800000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

      validation-query: select 1

  main:
    banner-mode: "off"
  jackson:
    time-zone: GMT+8
  data:
    redis:
      repositories:
        enabled: false
  redis:
    #数据库索引
    database:
    host:
    port: 6379
    #连接超时时间
    timeout: 5000

swagger:
  enabled: true

loginCode:
  expiration: 2