replicaCount: 1

resources:
  requests:
    cpu: 100m
    memory: 1536Mi
  limits:
    memory: 3072Mi
ingress:
  enabled: true
  hosts:
    - host: id-test.castlery.com
      paths:
        - "/"
  tls:
    - secretName: tls-castlery-com
      hosts:
        - id-test.castlery.com