{{- if gt (.Values.replicaCount | int) 1 }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ums-web.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "ums-web.name" . }}
    helm.sh/chart: {{ include "ums-web.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ums-web.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  minAvailable: 1
{{- end }}